<p style="align: center;"><img src="https://static.tildacdn.com/tild6636-3531-4239-b465-376364646465/Deep_Learning_School.png", width=600, height=300></p>

<h3 style="text-align: center;"><b>Школа глубокого обучения ФПМИ МФТИ</b></h3>

<h2 style="text-align: center;"><b>Домашнее задание. Библиотека <a href="http://pandas.pydata.org/">pandas</a></b></h2>

В этом задании вы проанализируете данные из Appstore

<img src="https://drive.google.com/uc?export=view&id=1F1Qajgj-dC4o4VI3Wm7fIGlOJA0a60_B" width=300 height=300>

In [ ]:
#!pip install pandas

In [1]:
# Подключить к google colab содержимое вашего google диск
from google.colab import drive
# This will prompt for authorization.
drive.mount('/content/drive')

Mounted at /content/drive

In [2]:
import pandas as pd
import numpy as np

### Данные для задания: https://drive.google.com/file/d/1JY8l5nSu9O4GtMDpaOfH2Oowlpza3U-c/view?usp=sharing

In [3]:
data = pd.read_csv('https://drive.google.com/uc?id=1JY8l5nSu9O4GtMDpaOfH2Oowlpza3U-c')

In [4]:
df = pd.read_csv('/content/drive/MyDrive/Colab Notebooks/BlackFriday.csv')

Посмотрим, что же такое переменная `data`:

In [31]:
data.head()

,User_ID,Product_ID,Gender,Age,Occupation,City_Category,Stay_In_Current_City_Years,Marital_Status,Product_Category_1,Product_Category_2,Product_Category_3,Purchase
0,1000001,P00069042,F,0-17,10,A,2,0,3,NaN,NaN,8370
1,1000001,P00248942,F,0-17,10,A,2,0,1,6.0,14.0,15200
2,1000001,P00087842,F,0-17,10,A,2,0,12,NaN,NaN,1422
3,1000001,P00085442,F,0-17,10,A,2,0,12,14.0,NaN,1057
4,1000002,P00285442,M,55+,16,C,4+,0,8,NaN,NaN,7969

In [7]:
type(data)

pandas.core.frame.DataFrame

---

#### Вопрос

О чём данные? (Hint: https://www.kaggle.com/sdolezel/black-friday)

---

#### Основное задание (в тесте надо будет вставлять ответы для этих пунктов):

*Примечание:* не бойтесь гуглить и заглядывать в "Полезные ссылки" для того, чтобы выполнить какие-то задания. Возможно, на семинаре не было какого-то нужного метода, но он находится в поисковике за 2 минуты.

**0).** Сколько всего возрастных категорий?

In [9]:
# Ваш код здесь
data['Age'].nunique()

7

**1).** Сколько строк с мужчинами из категории города A? (речь не об уникальных ID мужчин, а о количестве строк)

In [24]:
# Ваш код здесь
data.loc[(data['City_Category'] == 'A') & (data['Gender'] == 'M')]['Gender'].count()

109831

**2).** Сколько женщин от 46 до 50, потративших (столбец Purchase) больше 20000 (условных единиц, в данном случае)?   (речь не об уникальных ID, а о количестве строк)

In [29]:
# Ваш код здесь
data[(data['Age'] == '46-50') & (data['Gender'] == 'F') & (data['Purchase'] > 20000)]['Gender'].count()

270

**3).** Сколько NaN'ов в столбце Product_Category_3?

In [30]:
# Ваш код здесь
data['Product_Category_3'].isna().sum()

373299

**4).** Какую долю (вещественное число от 0 до 1, округлить до 4-го знака) от всех покупателей составляют ВМЕСТЕ мужчины от 26 до 35 лет и женщины старше 36 лет (то есть нужно учесть несколько возрастных категорий)? (речь не об уникальных ID, а о количестве таких строк)

In [54]:
# Ваш код здесь
round((data[((data['Age'] == '26-35') & (data['Gender'] == 'M')) | (~(data['Age'].isin(['0-17', '18-25', '26-35'])) & (data['Gender'] == 'F'))]['Gender'].count())/(data.shape[0]), 4)
# round((data[((data['Age'] == '26-35') & (data['Gender'] == 'M')) | ((data['Age'] > '36') & (data['Gender'] == 'F'))]['Gender'].count())/(data.shape[0]), 4)
# ((data.Age == '26-35') & (data.Gender == 'M') | (data.Gender == 'F') & (data.Age > '36')).mean().round(4)

0.4077

---

Больше про pandas можно найти по этом полезным ссылкам:

* Официальные туториалы: http://pandas.pydata.org/pandas-docs/stable/tutorials.html

* Статья на Хабре от [OpenDataScience сообщества](http://ods.ai/)**:** https://habr.com/company/ods/blog/322626/

* Подробный гайд: https://media.readthedocs.org/pdf/pandasguide/latest/pandasguide.pdf

Главное в работе с новыми библиотеками -- не бояться тыкать в разные функции, смотреть типы возвращаемых объектов и активно пользоваться Яндексом, а ещё лучше понимать всё из docstring'а (`Shift+Tab` при нахождении курсора внутри скобок функции).